# Generated by Django 3.1.2 on 2020-10-31 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('des', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 10, 31, 19, 45, 8, 505931))),
            ],
        ),
    ]
